name: namazvdom
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.10.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3
  dio: ^5.7.0
  just_audio: ^0.9.42
  google_fonts: ^8.0.1
  shared_preferences: ^2.5.4
  easy_localization: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
  -  assets/translations/
  -  assets/icons/back.svg
  -  assets/icons/slider-horizontal.svg
  -  assets/icons/play.svg
  -  assets/icons/pause.svg
  -  assets/icons/arrow-left.svg
  -  assets/icons/arrow-right.svg
  -  assets/images/
  -  assets/icons/salat.png
  -  assets/icons/salat-1.png
  -  assets/audio/istiaza.mp3
  -  assets/audio/takbir.mp3
  -  assets/icons/close-icon.svg
  -  assets/icons/arrow-bottom.svg
  -  assets/icons/check.svg
  -  assets/icons/more-circle.svg
  -  assets/icons/ablution.svg
  -  assets/icons/additional-prayers.svg
  -  assets/icons/numeration.svg
  -  assets/icons/arrow-right-chevron.svg
  -  assets/icons/bubbletail.svg
  
  -  assets/icons/planet.svg
  -  assets/icons/user.svg
  -  assets/icons/share.svg
  -  assets/icons/heart.svg
  -  assets/icons/mail.svg
  -  assets/icons/info.svg
  -  assets/icons/theme.svg
   
  -  assets/images/logo.png
  -  assets/images/logo-white.png
  -  assets/images/background.png
  -  assets/ablution/
  -  assets/ablution/images/
  -  assets/ablution/images/male/
  -  assets/ablution/images/female/
  -  assets/ablution/images/female/b_ablution_female_1.svg
  -  assets/ablution/images/female/b_ablution_female_2.svg
  -  assets/ablution/images/female/b_ablution_female_3.svg
  -  assets/ablution/images/female/b_ablution_female_4.svg
  -  assets/ablution/images/female/b_ablution_female_5.svg
  -  assets/ablution/images/female/b_ablution_female_6.svg
  -  assets/ablution/images/female/b_ablution_female_7.svg
  -  assets/ablution/images/female/b_ablution_female_8.svg
  -  assets/ablution/images/female/b_ablution_female_9.svg
  -  assets/ablution/images/female/w_ablution_female_1.svg
  -  assets/ablution/images/female/w_ablution_female_2.svg
  -  assets/ablution/images/female/w_ablution_female_3.svg
  -  assets/ablution/images/female/w_ablution_female_4.svg
  -  assets/ablution/images/female/w_ablution_female_5.svg
  -  assets/ablution/images/female/w_ablution_female_6.svg
  -  assets/ablution/images/female/w_ablution_female_7.svg
  -  assets/ablution/images/female/w_ablution_female_8.svg
  -  assets/ablution/images/female/w_ablution_female_9.svg
  -  assets/ablution/images/male/b_ablution_male_1.svg
  -  assets/ablution/images/male/b_ablution_male_2.svg
  -  assets/ablution/images/male/b_ablution_male_3.svg
  -  assets/ablution/images/male/b_ablution_male_4.svg
  -  assets/ablution/images/male/b_ablution_male_5.svg
  -  assets/ablution/images/male/b_ablution_male_6.svg
  -  assets/ablution/images/male/b_ablution_male_7.svg
  -  assets/ablution/images/male/b_ablution_male_8.svg
  -  assets/ablution/images/male/b_ablution_male_9.svg
  -  assets/ablution/images/male/w_ablution_male_1.svg
  -  assets/ablution/images/male/w_ablution_male_2.svg
  -  assets/ablution/images/male/w_ablution_male_3.svg
  -  assets/ablution/images/male/w_ablution_male_4.svg
  -  assets/ablution/images/male/w_ablution_male_5.svg
  -  assets/ablution/images/male/w_ablution_male_6.svg
  -  assets/ablution/images/male/w_ablution_male_7.svg
  -  assets/ablution/images/male/w_ablution_male_8.svg
  -  assets/ablution/images/male/w_ablution_male_9.svg
  -  assets/namaz/images/
  -  assets/namaz/images/at-tahiyat.svg
  -  assets/namaz/images/ruku.svg
  -  assets/namaz/images/seat.svg
  -  assets/namaz/images/stay.svg
  -  assets/namaz/images/sudjud.svg
  -  assets/namaz/images/takbir.svg
  -  assets/namaz/images/taslim-left.svg
  -  assets/namaz/images/taslim-right.svg
  -  assets/fajr/
  -  assets/dhuhr/
  -  assets/asr/
  -  assets/maghrib/
  -  assets/isha/
  -  assets/fajr/images/
  -  assets/surahs/
